namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_CURRENTLY_PLAYING_API: string;
    NEXT_PUBLIC_SPOTIFY_TOKEN: string;
    NEXT_PUBLIC_SPOTIFY_AUTH_CODE: string;
    NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN: string;
    NEXT_PUBLIC_SPOTIFY_CLIENT_ID: string;
    NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET: string;
    NEXT_PUBLIC_GOOGLE_ANALYTICS: string;
    NEXT_PUBLIC_SANITY_ID: string;
    NEXT_PUBLIC_SANITY_DATA_SETS: string;
    NEXT_PUBLIC_SANITY_API_VERSION: string;
    NEXT_PUBLIC_DATABASE_URL: string;
  }
}
